version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Tokyo
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Tokyo
    versioning-strategy: increase
    groups:
      babel:
        patterns:
          - "@babel/*"
          - babel-loader
      jest:
        patterns:
          - babel-jest
          - jest
          - jest-environment-jsdom
      storybook:
        patterns:
          - "@storybook/*"
          - storybook
      types:
        patterns:
          - "@types/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      vite:
        patterns:
          - "@vitejs/plugin-react"
          - vite
